[package]
name = "audiorust"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4"
vosk = "0.3"
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
zip = "0.6" 